version: '3.1'

services:

  db:
    image: postgres:10.8-alpine
    restart: always
    environment:
      POSTGRES_USER: ${USER_POSTGRES}
      POSTGRES_PASSWORD: ${PWD_POSTGRES}
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  # apitool:
  #   image: python:alpine
  #   restart: always
  #   volumes:
  #     - ${SERVER_PATH_SRC}:/usr/src
  #     - ${SERVER_PATH_SAMPLE}:/usr/src/sample


### execute
# docker-compose --env-file ./config/.env -f ./docker-compose.yml up -d
