version: '3.1'

services:
  apitest:
    image: apitest:1.1
    restart: always
    volumes:
      - type: bind
        source: ${SERVER_PATH_SRC}
        target: /usr/src
      - type: bind
        source: ${SERVER_PATH_SAMPLE}
        target: /usr/src/dataset
    networks:
      - front-network
      - db-network
    ports:
      - 9090:9090
    command: ["python", "main_restapi.py"]
    #command: ["tail", "-f", "/dev/null"]

  webserver:
    image: openjdk:8-jdk-alpine
    restart: always
    volumes:
      - type: bind
        source: ${WEB_SERVER_PATH_WAR}
        target: /usr/src
    networks:
      - front-network
    ports:
      - 9080:9080
    command: ["java", "-jar", "/usr/src/testweb-PRODUCTION.jar"]

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - db-network

  postgresql:
    image: postgres:10.8-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
    networks:
      - db-network
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ${POSTGRES_DATA_PATH}
        target: /var/lib/postgresql/data
    
networks:
  front-network:
  db-network:
